### ISSUE TITLE
AIS 4G esp32 error"collect2.exe: error:" 

### ISSUE THREAD

**Issue by jugkrit** [gravitech-engineer/AIS_IoT_4G#7]
Hi, 
I compile file "example>AIS_4G_board>azutre_IoT>4G>IOT_Central_sample"
But Arduino IDE show compile error as below. Could you help fix error.
Thank you
 
Arduino: 1.8.7 (Windows 10), Board: "ESP32 Dev Module, Disabled, Default 4MB with spiffs (1.2MB APP/1.5MB SPIFFS), 240MHz (WiFi/BT), QIO, 80MHz, 4MB (32Mb), 921600, Core 1, Core 1, None"

WARNING: Category '' in library ESP RainMaker is not valid. Setting to 'Uncategorized'
WARNING: Category '' in library WiFiProv is not valid. Setting to 'Uncategorized'
WARNING: Category 'Cellular Communication' in library Magellan_SIM7020E is not valid. Setting to 'Uncategorized'
WARNING: Category 'Cellular Communication' in library Magellan_SIM7020E is not valid. Setting to 'Uncategorized'
Invalid library found in C:\Users\tin\Documents\Arduino\libraries\Arduino-master: no headers files (.h) found in C:\Users\tin\Documents\Arduino\libraries\Arduino-master
Invalid library found in C:\Users\tin\Documents\Arduino\libraries\Grbl_Pen_Servo-master: no headers files (.h) found in C:\Users\tin\Documents\Arduino\libraries\Grbl_Pen_Servo-master
Invalid library found in C:\Users\tin\Documents\Arduino\libraries\NB-IoT-SIM700-MQTT-main: no headers files (.h) found in C:\Users\tin\Documents\Arduino\libraries\NB-IoT-SIM700-MQTT-main
C:\Users\tin\Documents\Arduino\libraries\AIS_4G_board\src\gsm_ssl_client.cpp:19:4: warning: #warning "Please configure IDF framework to include mbedTLS -> Enable pre-shared-key ciphersuites and activate at least one cipher" [-Wcpp]
 #  warning "Please configure IDF framework to include mbedTLS -> Enable pre-shared-key ciphersuites and activate at least one cipher"
    ^~~~~~~
c:/users/tin/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/gcc8_4_0-esp-2021r2-patch3/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: libraries\AIS_4G_board\GSMClientSecure.cpp.o:(.literal._ZN15GSMClientSecure5writeEPKhj+0x0): undefined reference to `gsm_send_ssl_data(gsm_sslclient_context*, unsigned char const*, unsigned int)'

c:/users/tin/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/gcc8_4_0-esp-2021r2-patch3/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: libraries\AIS_4G_board\GSMClientSecure.cpp.o:(.literal._ZN15GSMClientSecure9availableEv+0x4): undefined reference to `gsm_data_to_read(gsm_sslclient_context*)'

c:/users/tin/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/gcc8_4_0-esp-2021r2-patch3/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: libraries\AIS_4G_board\GSMClientSecure.cpp.o:(.literal._ZN15GSMClientSecure4readEPhj+0x0): undefined reference to `gsm_get_ssl_receive(gsm_sslclient_context*, unsigned char*, int)'

c:/users/tin/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/gcc8_4_0-esp-2021r2-patch3/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: libraries\AIS_4G_board\GSMClientSecure.cpp.o:(.literal._ZN15GSMClientSecure4stopEv+0x0): undefined reference to `gsm_stop_ssl_socket(gsm_sslclient_context*)'

c:/users/tin/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/gcc8_4_0-esp-2021r2-patch3/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: libraries\AIS_4G_board\GSMClientSecure.cpp.o:(.literal._ZN15GSMClientSecureC2Ev+0x8): undefined reference to `gsm_ssl_init(gsm_sslclient_context*)'

c:/users/tin/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/gcc8_4_0-esp-2021r2-patch3/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: libraries\AIS_4G_board\GSMClientSecure.cpp.o:(.literal._ZN15GSMClientSecure7connectEPKcti+0x0): undefined reference to `gsm_start_ssl_client(gsm_sslclient_context*, char const*, unsigned int, int, char const*, char const*, char const*, char const*, char const*, bool)'

c:/users/tin/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/gcc8_4_0-esp-2021r2-patch3/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: libraries\AIS_4G_board\GSMClientSecure.cpp.o: in function `GSMClientSecure::write(unsigned char const*, unsigned int)':

C:\Users\tin\Documents\Arduino\libraries\AIS_4G_board\src/GSMClientSecure.cpp:97: undefined reference to `gsm_send_ssl_data(gsm_sslclient_context*, unsigned char const*, unsigned int)'

c:/users/tin/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/gcc8_4_0-esp-2021r2-patch3/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: libraries\AIS_4G_board\GSMClientSecure.cpp.o: in function `GSMClientSecure::available()':

C:\Users\tin\Documents\Arduino\libraries\AIS_4G_board\src/GSMClientSecure.cpp:109: undefined reference to `gsm_data_to_read(gsm_sslclient_context*)'

c:/users/tin/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/gcc8_4_0-esp-2021r2-patch3/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: libraries\AIS_4G_board\GSMClientSecure.cpp.o: in function `GSMClientSecure::read(unsigned char*, unsigned int)':

C:\Users\tin\Documents\Arduino\libraries\AIS_4G_board\src/GSMClientSecure.cpp:143: undefined reference to `gsm_get_ssl_receive(gsm_sslclient_context*, unsigned char*, int)'

c:/users/tin/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/gcc8_4_0-esp-2021r2-patch3/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: libraries\AIS_4G_board\GSMClientSecure.cpp.o: in function `GSMClientSecure::stop()':

C:\Users\tin\Documents\Arduino\libraries\AIS_4G_board\src/GSMClientSecure.cpp:183: undefined reference to `gsm_stop_ssl_socket(gsm_sslclient_context*)'

c:/users/tin/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/gcc8_4_0-esp-2021r2-patch3/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: libraries\AIS_4G_board\GSMClientSecure.cpp.o: in function `gsm_sslclient_context::gsm_sslclient_context()':

C:\Users\tin\Documents\Arduino\libraries\AIS_4G_board\src/gsm_ssl_client.h:17: undefined reference to `gsm_ssl_init(gsm_sslclient_context*)'

c:/users/tin/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/gcc8_4_0-esp-2021r2-patch3/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: libraries\AIS_4G_board\GSMClientSecure.cpp.o: in function `GSMClientSecure::connect(char const*, unsigned short, int)':

C:\Users\tin\Documents\Arduino\libraries\AIS_4G_board\src/GSMClientSecure.cpp:74: undefined reference to `gsm_start_ssl_client(gsm_sslclient_context*, char const*, unsigned int, int, char const*, char const*, char const*, char const*, char const*, bool)'

collect2.exe: error: ld returned 1 exit status
exit status 1
Error compiling for board ESP32 Dev Module.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by vixtory09678** [comment]
I have the same problem but I already solved it. Please, waiting for this PR merge. [fix: update key exchange header checker according to WiFiClientSecure #8](https://github.com/gravitech-engineer/AIS_IoT_4G/pull/8)

**Comment by maxpromer** [comment]
Fixed in V1.0.3

**Comment by jugkrit** [comment]
> Fixed in V1.0.3

Which software V1.0.3?

**Comment by maxgerhardt** [comment]
https://github.com/gravitech-engineer/AIS_IoT_4G/releases/tag/V1.0.3
